User.destroy_all

User.create([
	{
		email:"tom@toms.com",
		password:"123",
		password_confirmation:"123"
	},
	{
		email:"bob@bob.com",
		password:"122",
		password_confirmation:"122"
	},
	{
		email:"mom@bomb.com",
		password:"1234",
		password_confirmation:"1234"
	}
	])